sudo: required
services:
    - docker
before_install:
    - docker build -t hwlow/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run hwlow/react-test npm test -- --coverage


after_success:
    - docker build -t hwlow/multi-client ./client
    - docker build -t hwlow/multi-nginx ./nginx
    - docker build -t hwlow/multi-server ./server
    - docker build -t hwlow/multi-worker ./worker
   #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub



    - docker push hwlow/multi-client
    - docker push hwlow/multi-nginx
    - docker push hwlow/multi-server
    - docker push hwlow/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-213758627586
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
